import { redirect } from "next/navigation";
import { requireTenantSession } from "@/lib/auth";
import { completeOnboardingAction } from "@/app/actions/onboarding";

export default async function OnboardingPage(){const {tenant}=await requireTenantSession();if(tenant.onboardingDone)redirect("/app");return <><div className="page-title"><span className="eyebrow">Puesta en marcha</span><h1>Publicá tu primera agenda</h1><p className="muted">Completá estos datos y dejaremos un servicio listo para recibir reservas.</p></div><form action={completeOnboardingAction} className="grid two-col">
  <div className="card"><span className="pill">1 · Negocio</span><div className="field"><label>Nombre comercial</label><input className="input" name="businessName" defaultValue={tenant.name} required/></div><div className="field"><label>Rubro</label><input className="input" name="category" placeholder="Ej. salud, deporte, servicios" required/></div><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field"><label>Zona horaria</label><input className="input" name="timezone" defaultValue={tenant.timezone} required/></div><div className="field"><label>Moneda</label><input className="input" name="currency" defaultValue={tenant.currency} maxLength={3} required/></div></div></div>
  <div className="card"><span className="pill">2 · Sucursal</span><div className="field"><label>Nombre</label><input className="input" name="locationName" defaultValue="Principal" required/></div><div className="field"><label>Dirección</label><input className="input" name="address" placeholder="Dirección visible para clientes"/></div></div>
  <div className="card"><span className="pill">3 · Servicio</span><div className="field"><label>Nombre del primer servicio</label><input className="input" name="serviceName" required/></div><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field"><label>Duración (min)</label><input className="input" name="durationMinutes" type="number" min="5" defaultValue="30" required/></div><div className="field"><label>Precio</label><input className="input" name="price" type="number" min="0" step="0.01" defaultValue="0" required/></div></div></div>
  <div className="card"><span className="pill">4 · Asignación</span><div className="field"><label>¿Quién o qué atiende?</label><select className="select" name="assigneeType"><option value="PROFESSIONAL">Profesional</option><option value="RESOURCE">Recurso</option></select></div><div className="field"><label>Nombre</label><input className="input" name="assigneeName" placeholder="Ej. Ana o Consultorio 1" required/></div></div>
  <div className="card"><span className="pill">5 · Horarios</span><p className="muted">Lunes a viernes. Podrás agregar excepciones luego.</p><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field"><label>Apertura</label><input className="input" name="openingTime" type="time" defaultValue="09:00" required/></div><div className="field"><label>Cierre</label><input className="input" name="closingTime" type="time" defaultValue="18:00" required/></div></div></div>
  <div className="card"><span className="pill">6 · Identidad</span><div className="field"><label>Color principal</label><input className="input" name="primaryColor" type="color" defaultValue="#5b5cf0" required/></div><div className="field"><label>Descripción pública</label><textarea className="input" name="description" rows={3} placeholder="Contale al cliente qué ofrecés"/></div></div>
  <div className="card" style={{gridColumn:"1/-1",textAlign:"center"}}><span className="eyebrow">7 · Revisar · 8 · Publicar</span><h2>Todo listo para crear tu agenda</h2><p className="muted">Podrás editar cada dato desde el panel.</p><button className="button" style={{minWidth:240}}>Crear y publicar agenda</button></div>
 </form></>}
