import { requireTenantSession } from "@/lib/auth";
import { createTenantDb } from "@/lib/tenant-db";
import { createLocationAction, createProfessionalAction, createResourceAction, createServiceAction } from "@/app/actions/catalog";

export default async function CatalogPage(){
  const {membership,tenant}=await requireTenantSession();
  const [locations,services,professionals,resources]=await createTenantDb(membership.tenantId).catalog();
  const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:tenant.currency,maximumFractionDigits:0});
  return <><div className="page-title"><span className="eyebrow">Catálogo</span><h1>Servicios y equipo</h1><p className="muted">Personas y recursos conviven en el mismo motor de reservas.</p></div>
    <details className="card"><summary style={{cursor:"pointer",fontWeight:750}}>Agregar al catálogo</summary><div className="grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))",marginTop:16}}>
      <form action={createServiceAction} className="card" style={{boxShadow:"none"}}><h3>Servicio</h3><div className="field"><label>Nombre</label><input className="input" name="name" required/></div><div className="field"><label>Descripción</label><input className="input" name="description"/></div><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><input className="input" aria-label="Duración" name="durationMinutes" type="number" min="5" defaultValue="30" required/><input className="input" aria-label="Precio" name="price" type="number" min="0" step="0.01" defaultValue="0" required/></div><div className="field"><label>Sucursal</label><select className="select" name="locationId" required>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><select className="select" aria-label="Profesional" name="professionalId"><option value="">Sin profesional</option>{professionals.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select className="select" aria-label="Recurso" name="resourceId"><option value="">Sin recurso</option>{resources.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><button className="button">Crear servicio</button></form>
      <div className="grid">
        <form action={createProfessionalAction} className="card" style={{boxShadow:"none"}}><h3>Profesional</h3><input className="input" name="name" placeholder="Nombre" required/><select className="select" name="locationId"><option value="">Todas las sucursales</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input name="color" type="color" defaultValue="#5b5cf0"/><button className="button secondary">Agregar</button></form>
        <form action={createResourceAction} className="card" style={{boxShadow:"none"}}><h3>Recurso</h3><input className="input" name="name" placeholder="Nombre" required/><input className="input" name="type" placeholder="Tipo (sala, cancha, box…)"/><select className="select" name="locationId"><option value="">Todas las sucursales</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input className="input" name="capacity" type="number" min="1" defaultValue="1"/><input name="color" type="color" defaultValue="#10b981"/><button className="button secondary">Agregar</button></form>
        <form action={createLocationAction} className="card" style={{boxShadow:"none"}}><h3>Sucursal</h3><input className="input" name="name" placeholder="Nombre" required/><input className="input" name="address" placeholder="Dirección"/><button className="button secondary">Agregar</button></form>
      </div>
    </div></details>
    <div className="grid two-col"><div className="card"><div className="section-head"><h2>Servicios</h2><span className="pill">{services.length} activos</span></div>{services.map(service=><div className="booking-row" key={service.id}><div className="avatar" style={{background:service.color}}>{service.name[0]}</div><div><strong>{service.name}</strong><div className="muted" style={{fontSize:12}}>{service.durationMinutes} min · {service.category??"General"}</div></div><strong>{service.priceCents==null?"Consultar":money.format(service.priceCents/100)}</strong></div>)}</div>
      <div className="grid"><div className="card"><div className="section-head"><h2>Profesionales</h2><span className="pill">{professionals.length}</span></div>{professionals.map(item=><p key={item.id}><span className="dot" style={{background:item.color}}/>{item.name}</p>)}</div><div className="card"><div className="section-head"><h2>Recursos</h2><span className="pill">{resources.length}</span></div>{resources.map(item=><p key={item.id}><span className="dot" style={{background:item.color}}/>{item.name} <span className="muted">· cupo {item.capacity}</span></p>)}</div><div className="card"><div className="section-head"><h2>Sucursales</h2><span className="pill">{locations.length}</span></div>{locations.map(item=><p key={item.id}><strong>{item.name}</strong><br/><span className="muted">{item.address}</span></p>)}</div></div></div>
  </>;
}
